# Uncomment this line to define a global platform for your project
platform :ios, '8.0'


workspace '../../LeChat/LeChat.xcworkspace'
project '../../LeChat/LeChat.xcodeproj'

target 'LeChat' do
  


    pod 'React', :path => '../../LeChat/React/node_modules/react-native', :subspecs => [
    
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    
    ]

end



#pod install --verbose --no-repo-update
#pod update --verbose --no-repo-update
